-- ============================================================
-- PHASE 4: ORACLE DATABASE CREATION
-- Database: mberaMuganga_db
-- Student: benon
-- ID: 29143
-- Project: Mbera Muganga (Patient Management System)
-- ============================================================

-- 1. CREATE TABLESPACES
CREATE TABLESPACE MBERA_DATA
DATAFILE 'mbera_data01.dbf'
SIZE 200M
AUTOEXTEND ON NEXT 50M
MAXSIZE 1G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE MBERA_IDX
DATAFILE 'mbera_idx01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 25M
MAXSIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE MBERA_TEMP
TEMPFILE 'mbera_temp01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 25M
MAXSIZE 300M;

CREATE UNDO TABLESPACE MBERA_UNDO
DATAFILE 'mbera_undo01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 25M
MAXSIZE 500M;

