-- 1. CREATE ADMIN USER (as specified in requirements)
CREATE USER tue_29143_benon_mberaMuganga_admin 
IDENTIFIED BY benon  -- Password = Your first name (as per requirements)
DEFAULT TABLESPACE MBERA_DATA
TEMPORARY TABLESPACE MBERA_TEMP
QUOTA UNLIMITED ON MBERA_DATA
QUOTA UNLIMITED ON MBERA_IDX
ACCOUNT UNLOCK;

-- 2. GRANT PRIVILEGES (Super admin privileges)
GRANT CONNECT, RESOURCE TO tue_29143_benon_mberaMuganga_admin;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE,
      CREATE TYPE, CREATE DATABASE LINK TO tue_29143_benon_mberaMuganga_admin;
GRANT DBA TO tue_29143_benon_mberaMuganga_admin;  -- Super admin as required

-- 3. CONNECT AS THE ADMIN USER
-- First disconnect, then reconnect with the new user
DISCONNECT;
CONNECT tue_29143_benon_mberaMuganga_admin/benon;

-- 4. CREATE SEQUENCES FOR PRIMARY KEYS
CREATE SEQUENCE patient_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE doctor_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE report_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE appointment_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE medication_seq START WITH 1 INCREMENT BY 1 NOCACHE;

